add baseline file generation

diff --git a/.github/workflows/main_branch.yml b/.github/workflows/main_branch.yml
--- a/.github/workflows/main_branch.yml
+++ b/.github/workflows/main_branch.yml
@@ -91,6 +91,61 @@ jobs:
           scan-results-json: '/tmp/policy_flaws.json'
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
+  veracode-pipeline-scan:
+    needs: policy-scan
+    runs-on: ubuntu-latest
+    container: 
+      image: veracode/pipeline-scan:latest
+      options: --user root
+    steps:
+      - name: get archive
+        uses: actions/download-artifact@v2
+        with:
+          name: verademo.war
+          path: /tmp
+      - name: pipeline-scan
+        run: | 
+          java -jar /opt/veracode/pipeline-scan.jar \
+            -vid "${{secrets.VERACODE_API_ID}}" \
+            -vkey "${{secrets.VERACODE_API_KEY}}" \
+            --fail_on_severity="Very High, High" \
+            --file /tmp/verademo.war \
+            -jf results.json \
+            -fjf filtered_results.json 
+        continue-on-error: true
+
+      - name: save standard results
+        uses: actions/upload-artifact@v1
+        with:
+          name: PipelineScanResults
+          path: results.json
+      - name: save filtered results
+        uses: actions/upload-artifact@v1
+        with:
+          name: filtered-results
+          path: filtered_results.json
+
+  commit-baseline-file:
+    needs: veracode-pipeline-scan
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: get scan results
+      uses: actions/download-artifact@v2
+      with:
+        name: PipelineScanResults
+    - name: commit baseline file to feature branches
+      run: |
+        git config --global user.name "julz0815"
+        git config --global user.email "username@users.noreply.github.com"
+        git add "results.json"
+        git stash
+        git pull origin feature-123 || echo "Couldn't find remote branch"
+        git checkout stash -- .
+        git commit -m "Veracode Baseline File push from pipeline"
+        git push origin HEAD:feature-123 --force-with-lease
+
   veracode-sca-task:
     runs-on: ubuntu-latest
     name: Scan repository for Issues
